# Author: Harshit Kandpal <hkandpal944@gmail.com>

services:
  # A user-defined name for this container
  flask-app:
    container_name: assistant-container_flask-app
    # Indicates that `Dockerfile-dev` should be used for local instantiations
    build:
        context: .
        dockerfile: Dockerfile-dev
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
    # Mounts the local directory to docker container as a volume.
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - FLASK_DEBUG=${FLASK_DEBUG}
      - APP_SECRET_KEY=${APP_SECRET_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - spartynet

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - spartynet

networks:
  spartynet:
    driver: bridge