# Author: Harshit Kandpal <hkandpal944@gmail.com>
# Access instance using `docker exec -it assistant-container_flask-app bash`

# Instantiate Ubuntu 20.04
FROM ubuntu:20.04
LABEL maintainer="Harshit Kandpal <hkandpal944@gmail.com>"
LABEL description="This is a custom Docker Image for Harshit Kandpal's Web Application Projects"

# Update Ubuntu Software repository
RUN apt update
RUN apt-get update -qq

# Install MySQL and create the database
ENV TZ=America/New_York
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get install -y mysql-server 
RUN service mysql start && mysql -e "CREATE USER 'master'@'localhost' IDENTIFIED BY 'master';CREATE DATABASE db; GRANT ALL PRIVILEGES ON db.* TO 'master'@'localhost';"
#RUN service mysql start && mysql -e "CREATE USER 'master'@'localhost' IDENTIFIED BY 'master';CREATE DATABASE db; GRANT SUPER ON *.* TO 'master'@'localhost';"

# Add the Flask application and install requirements
RUN apt -y install python3-pip python3-venv python3-dev build-essential libmysqlclient-dev
RUN apt -y install vim
RUN mkdir /app
COPY . /app
WORKDIR /app
RUN pip3 install --upgrade pip
RUN pip3 install --no-cache-dir -r requirements.txt

# Open ports, set environment variables, start the application.
EXPOSE 8080 
ENV PORT=8080

#EXPOSE 3336 
#ENV PORT 3336

ENV FLASK_ENV=production
CMD service mysql start && exec python3 app.py
# ----------------------------------------------------- 